---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy: {}
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: registry
        name: registry
        env:
        - name: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
          value: "false"
        resources: {}
        ports:
        - containerPort: 5000      
        volumeMounts:
        - mountPath: "/var/lib/registry"
          name: registry
      volumes:
        - name: registry
          persistentVolumeClaim:
            claimName: registry
