apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: default
  labels:
    nfs: registry
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /media/mybook/k8sNFS/docker-registry/
    server: 192.168.1.142
