apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - registry-192.168.1.38.nip.io
    secretName: registry-ingress-tls
  rules:
  - host: registry-192.168.1.38.nip.io
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: registry
              port:
                number: 80
