apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - registry-192.168.1.38.nip.io
    secretName: registry-ingress-tls
  rules:
  - host: registry-192.168.1.38.nip.io
  - http:
      paths:
        - backend:
            serviceName: registry
            servicePort: 80

